### ISSUE TITLE
Spark cluster credentials configuration

### ISSUE THREAD

**Issue by nilyin** [yummyml/yummy#7]
Hi, I can't find how to connect with yummy plugin to standalone Spark cluster? 
Where auth params (url, user, password or token) can be configured?
Is it supported?

**Comment by qooba** [comment]
Hi @nilyin  you can put spark configuration into `feature_store.yaml` file
`offline_store.config` block will be used during spark session creation:
```
project: feature_repo
registry: data/registry.db
provider: local
online_store:
    ...
offline_store:
    type: yummy.YummyOfflineStore
    backend: spark
    config:
        spark.master: "local[*]"
        spark.ui.enabled: "false"
        spark.eventLog.enabled: "false"
        spark.sql.session.timeZone: "UTC"

```

**Comment by nilyin** [comment]
hi, thank you for you response. As I understand there are 3 ways of how Feast (Yummy plugin) can pass authentication params to Spark:

1) config:
`spark.authenticate.secret      SomeSecretKey`

2) via Spark Context:
`val conf = new SparkConf()
      .set("spark.authenticate.secret", "SomeSecretKey")
val sc = new SparkContext(conf)`


3) via Spark Session:
`val spark = SparkSession.builder()
    .conf("spark.authenticate.secret", "SomeSecretKey")
    .getOrCreate()`

which of the above-mentioned ways are supported by Yummy plugin and what declarative format should I use in `offline_store.config` block for secure credentials, for those to be picked up by Yummy plugin and sent to Spark cluster? Can you please give a working config example I can try?

Thank you again, N.

**Comment by qooba** [comment]
Hi @nilyin,
It depends how you start spark session:

1) If you use `pyspark` you simple specify configuration there:
```
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --notebook-dir=/home/jovyan --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.password='' --NotebookApp.token=''"
pyspark \
    --master spark://spark-master:7077 \
    --packages org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.2,io.delta:delta-core_2.12:1.1.0,org.apache.hadoop:hadoop-aws:3.3.1,software.amazon.awssdk:s3:2.17.131 \
    --conf "spark.authenticate.secret=SomeSecretKey" \
    --conf "spark.authenticate=true"
```

And `yummy` will simply reuse already created session:
https://github.com/yummyml/yummy/blob/master/yummy/backends/spark.py#L243
```
    def _get_spark_session(
        self,
        backend_config: BackendConfig,
    ) -> SparkSession:
        spark_session = SparkSession.getActiveSession()

        if not spark_session:
            spark_builder = SparkSession.builder
            spark_conf = backend_config.config

            if spark_conf:
                spark_builder = spark_builder.config(
                    conf=SparkConf().setAll(spark_conf.items())
                )  # noqa

            spark_session = spark_builder.getOrCreate()

        return spark_session
```

If you use `spark-submit` eg.:
```bash
export PYSPARK_DRIVER_PYTHON=python3
spark-submit \
    --master spark://spark-master:7077 \
    --packages org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.2,io.delta:delta-core_2.12:1.1.0,org.apache.hadoop:hadoop-aws:3.3.1,software.amazon.awssdk:s3:2.17.131 \
    ./pyspark_test.py
```

the new spark session will be created according to the `yummy` configuration:
`feature_store.yaml`
```yaml
project: repo
registry: s3://yummy/data/registry.db
provider: yummy.YummyProvider
backend: spark
online_store:
    type: redis
    connection_string: "redis:6379"
offline_store:
    type: yummy.YummyOfflineStore    
    config:
        spark.master: "spark://spark-master:7077"
        spark.authenticate.secret: "SomeSecretKey"
        spark.authenticate: "true"
```
